version: "3.8"
services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # WordPress (frontend + php-fpm + apache)
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:80"
    volumes:
      - ./wp-plugins:/var/www/html/wp-content/plugins:cached
      - ./wp-themes:/var/www/html/wp-content/themes:cached
      - ./wp-uploads:/var/www/html/wp-content/uploads:cached
      - ./wp-config.php:/var/www/html/wp-config.php:ro
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DEBUG: "1"
      XDEBUG_MODE: debug
      XDEBUG_CLIENT_HOST: host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Mail testing
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1026:1025" # smtp
      - "8026:8025" # web ui

volumes:
  db_data:
